### PR TITLE
Feature: Hard limit for NFT minting

### PR DESCRIPTION
**Pull request by chexware**
@justinphamnz Here is the implementation of the hard limit for NFT minting per  NFT class. These 2 require to be

- [x] Appropriate NftClassData storage migration which sets accurate total minted tokens amount for existing NFT classes

Let me know if anything else needs changing.

### CODE REVIEW

**Comment by justinphamnz** [comment]
> @justinphamnz Here is the implementation of the hard limit for NFT minting per NFT class. These 2 require to be
> 
> * [ ]  Appropriate NftClassData storage migration which sets accurate total minted tokens amount for existing NFT classes
> * [ ]  Updated NFT asset minting workflow that allows setting issue number for each minted token
> 
> Let me know if anything else needs changing.

Hi @chexware,

Is this PR ready for review?

**Comment by chexware** [comment]
> > @justinphamnz Here is the implementation of the hard limit for NFT minting per NFT class. These 2 require to be
> > 
> > * [ ]   Appropriate NftClassData storage migration which sets accurate total minted tokens amount for existing NFT classes
> > * [ ]   Updated NFT asset minting workflow that allows setting issue number for each minted token
> > 
> > Let me know if anything else needs changing.
> 
> Hi @chexware,
> 
> Is this PR ready for review?

@justinphamnz  so the initial hard limit logic is working. However, I still need to finish the tasks from the to-do list but this could be done in a separate PR if needed

**Comment by chexware** [comment]
@justinphamnz  perhaps this branch could be merged at its current state and I will make the changes to the asset minting workflow that will add the issue number for every minted NFT of a class  on a separate branch

**Review by justinphamnz — APPROVED** [review]
LGTM. Thanks @chexware.

This requires storage migration, could be done in separate PR.

**Comment by chexware** [comment]
> LGTM. Thanks @chexware.
> 
> This requires storage migration, could be done in separate PR.

I've updated the storage migration to find total minted tokens so far in this PR but let me know if anything needs to be added/changed there.

**Comment by justinphamnz** [comment]
> > LGTM. Thanks @chexware.
> > This requires storage migration, could be done in separate PR.
> 
> I've updated the storage migration to find total minted tokens so far in this PR but let me know if anything needs to be added/changed there.

That's great. This is breaking changes that cause disruption in integration so we need to ensure API and SDK are also updated before merging and performing upgrades.

**Review by justinphamnz — APPROVED** [review]

**Pull request merged**
